name: Testar Projeto
on:
  push:
    branches: 
      "main"

jobs:
  teste:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.14.x]

    steps: 
      - name: Obter Repositório
        uses: actions/checkout@v3
      - name: Instalar NodeJs
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Instalar Dependências
        run: npm ci
      - name: Testes
        run: npm run test
